FROM python:3.8-alpine

RUN apk add --no-cache netcat-openbsd

RUN pip3 install flask \
  && pip3 install flask-restful \
  && pip3 install flask_sqlalchemy \
  && pip3 install pbkdf2 \
  && pip3 install flask-mail \
  && rm -rf /root/.cache

COPY my_script.py /
COPY config.py /
COPY resource.csv /
COPY app /app

CMD [ "python", "./my_script.py" ]
